package race

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

var data = []struct {
	log      string
	redacted string
}{
	{
		`WARNING: DATA RACE
Read at 0x00c00321e988 by goroutine 96:
  reflect.typedmemmove()
      /usr/local/go/src/runtime/mbarrier.go:203 +0x0
  reflect.copyVal()
      /usr/local/go/src/reflect/value.go:2064 +0x5b
  reflect.(*MapIter).Value()
      /usr/local/go/src/reflect/value.go:1961 +0x124
  encoding/json.mapEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:749 +0x61a
  encoding/json.mapEncoder.encode-fm()
      <autogenerated>:1 +0x84
  encoding/json.(*encodeState).reflectValue()
      /usr/local/go/src/encoding/json/encode.go:321 +0x83
  encoding/json.(*encodeState).marshal()
      /usr/local/go/src/encoding/json/encode.go:297 +0xea
  encoding/json.Marshal()
      /usr/local/go/src/encoding/json/encode.go:163 +0x12b
  github.com/kubeshark/worker/pkg/watchdog.tracerSnifferProgressTestFunc()
      /app/pkg/watchdog/tests.go:115 +0x6d9
  github.com/kubeshark/worker/pkg/watchdog.(*StatefulTest).Run()
      /app/pkg/watchdog/statefultest.go:75 +0x306
  github.com/kubeshark/worker/pkg/watchdog.(*Watchdog).runTests()
      /app/pkg/watchdog/statefultest.go:210 +0x108
  github.com/kubeshark/worker/pkg/watchdog.(*Watchdog).run()
      /app/pkg/watchdog/statefultest.go:196 +0x166
  github.com/kubeshark/worker/pkg/watchdog.(*Watchdog).Start.gowrap1()
      /app/pkg/watchdog/statefultest.go:148 +0x33

Previous write at 0x00c00321e988 by goroutine 90:
  encoding/json.(*decodeState).objectInterface()
      /usr/local/go/src/encoding/json/decode.go:1097 +0x1f9
  encoding/json.(*decodeState).object()
      /usr/local/go/src/encoding/json/decode.go:616 +0xa64
  encoding/json.(*decodeState).value()
      /usr/local/go/src/encoding/json/decode.go:374 +0xae
  encoding/json.(*decodeState).unmarshal()
      /usr/local/go/src/encoding/json/decode.go:181 +0x2d6
  encoding/json.Unmarshal()
      /usr/local/go/src/encoding/json/decode.go:108 +0x22b
  github.com/kubeshark/worker/pkg/health.readTracerStats()
      /app/pkg/health/health.go:665 +0x21d
  github.com/kubeshark/worker/pkg/health.(*healthConfig).ensureHealth()
      /app/pkg/health/health.go:161 +0x964
  github.com/kubeshark/worker/pkg/health.EnsureHealthEvery10s()
      /app/pkg/health/health.go:99 +0x3b6
  main.run.gowrap1()
      /app/main.go:275 +0x46

Goroutine 96 (running) created at:
  github.com/kubeshark/worker/pkg/watchdog.(*Watchdog).Start()
      /app/pkg/watchdog/statefultest.go:148 +0xa5
  github.com/kubeshark/worker/pkg/watchdog.Start()
      /app/pkg/watchdog/statefultest.go:181 +0x350
  main.run()
      /app/main.go:300 +0xe44
  main.main()
      /app/main.go:207 +0x1653
  runtime.main()
      /usr/local/go/src/runtime/proc.go:271 +0x29c
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.validate()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:15 +0xee
  github.com/alecthomas/participle/v2.Build[go.shape.struct { Logical *github.com/kubeshark/kfl.Logical "@@" }]()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/parser.go:131 +0x52c
  github.com/alecthomas/participle/v2.MustBuild[go.shape.struct { Logical *github.com/kubeshark/kfl.Logical "@@" }]()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/parser.go:53 +0x469
  github.com/kubeshark/kfl.init()
      /root/.cache/go-build/github.com/kubeshark/kfl@v1.0.10/parser.go:78 +0x41c

Goroutine 90 (running) created at:
  main.run()
      /app/main.go:275 +0xb2f
  main.main()
      /app/main.go:207 +0x1653
  runtime.main()
      /usr/local/go/src/runtime/proc.go:271 +0x29c
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:26 +0x168
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:34 +0x3c8
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:48 +0xba
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:13 +0x5bd
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:30 +0x372
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:19 +0x214
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.visit.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:40 +0x284
  github.com/alecthomas/participle/v2.isLeftRecursive.func2()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:52 +0x19b
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.isLeftRecursive()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:33 +0x169
  github.com/alecthomas/participle/v2.validate.func1()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:17 +0xb4
  github.com/alecthomas/participle/v2.visit()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/visit.go:9 +0xec
  github.com/alecthomas/participle/v2.validate()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/validate.go:15 +0xee
  github.com/alecthomas/participle/v2.Build[go.shape.struct { Logical *github.com/kubeshark/kfl.Logical "@@" }]()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/parser.go:131 +0x52c
  github.com/alecthomas/participle/v2.MustBuild[go.shape.struct { Logical *github.com/kubeshark/kfl.Logical "@@" }]()
      /root/.cache/go-build/github.com/alecthomas/participle/v2@v2.1.1/parser.go:53 +0x469
  github.com/kubeshark/kfl.init()
      /root/.cache/go-build/github.com/kubeshark/kfl@v1.0.10/parser.go:78 +0x41c`,
		`WARNING: DATA RACE
Read at [REDACTED] by [REDACTED]:
  reflect.typedmemmove()
      /usr/local/go/src/runtime/mbarrier.go:203 +[REDACTED]
  reflect.copyVal()
      /usr/local/go/src/reflect/value.go:2064 +[REDACTED]
  reflect.(*MapIter).Value()
      /usr/local/go/src/reflect/value.go:1961 +[REDACTED]
  encoding/json.mapEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:749 +[REDACTED]
  encoding/json.mapEncoder.encode-fm()
      <autogenerated>:1 +[REDACTED]
  encoding/json.(*encodeState).reflectValue()
      /usr/local/go/src/encoding/json/encode.go:321 +[REDACTED]
  encoding/json.(*encodeState).marshal()
      /usr/local/go/src/encoding/json/encode.go:297 +[REDACTED]
  encoding/json.Marshal()
      /usr/local/go/src/encoding/json/encode.go:163 +[REDACTED]
  github.com/kubeshark/worker/pkg/watchdog.tracerSnifferProgressTestFunc()
      /app/pkg/watchdog/tests.go:115 +[REDACTED]
  github.com/kubeshark/worker/pkg/watchdog.(*StatefulTest).Run()
      /app/pkg/watchdog/statefultest.go:75 +[REDACTED]
  github.com/kubeshark/worker/pkg/watchdog.(*Watchdog).runTests()
      /app/pkg/watchdog/statefultest.go:210 +[REDACTED]
  github.com/kubeshark/worker/pkg/watchdog.(*Watchdog).run()
      /app/pkg/watchdog/statefultest.go:196 +[REDACTED]
  github.com/kubeshark/worker/pkg/watchdog.(*Watchdog).Start.gowrap1()
      /app/pkg/watchdog/statefultest.go:148 +[REDACTED]

Previous write at [REDACTED] by [REDACTED]:
  encoding/json.(*decodeState).objectInterface()
      /usr/local/go/src/encoding/json/decode.go:1097 +[REDACTED]
  encoding/json.(*decodeState).object()
      /usr/local/go/src/encoding/json/decode.go:616 +[REDACTED]
  encoding/json.(*decodeState).value()
      /usr/local/go/src/encoding/json/decode.go:374 +[REDACTED]
  encoding/json.(*decodeState).unmarshal()
      /usr/local/go/src/encoding/json/decode.go:181 +[REDACTED]
  encoding/json.Unmarshal()
      /usr/local/go/src/encoding/json/decode.go:108 +[REDACTED]
  github.com/kubeshark/worker/pkg/health.readTracerStats()
      /app/pkg/health/health.go:665 +[REDACTED]
  github.com/kubeshark/worker/pkg/health.(*healthConfig).ensureHealth()
      /app/pkg/health/health.go:161 +[REDACTED]
  github.com/kubeshark/worker/pkg/health.EnsureHealthEvery10s()
      /app/pkg/health/health.go:99 +[REDACTED]
  main.run.gowrap1()
      /app/main.go:275 +[REDACTED]`,
	},
	{
		`WARNING: DATA RACE
Write at 0x0000080b1f80 by goroutine 129:
  github.com/kubeshark/hub/server/license.AddNode()
      /app/server/license/nodes.go:13 +0x172
  github.com/kubeshark/hub/pkg/kubernetes.(*Watcher).handleNodeObject()
      /app/pkg/kubernetes/watcher.go:1043 +0xe6
  github.com/kubeshark/hub/pkg/kubernetes.(*Watcher).watchAllNodes.func3()
      /app/pkg/kubernetes/watcher.go:489 +0x6f
  k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/controller.go:239 +0x63
  k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
      <autogenerated>:1 +0x1b
  k8s.io/client-go/tools/cache.(*processorListener).run.func1()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:978 +0x2a1
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:226 +0x41
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:227 +0xc4
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:204 +0x10a
  k8s.io/apimachinery/pkg/util/wait.Until()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:161 +0x9b
  k8s.io/client-go/tools/cache.(*processorListener).run()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:972 +0x38
  k8s.io/client-go/tools/cache.(*processorListener).run-fm()
      <autogenerated>:1 +0x33
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:72 +0x86

Previous read at 0x0000080b1f80 by goroutine 68:
  github.com/kubeshark/hub/server/license.GetNodeCount()
      /app/server/license/nodes.go:40 +0x61c
  github.com/kubeshark/hub/server/license.Check()
      /app/server/license/license.go:143 +0x5d1
  github.com/kubeshark/hub/pkg/kubernetes.SyncSecret()
      /app/pkg/kubernetes/config.go:637 +0x297
  github.com/kubeshark/hub/pkg/kubernetes.(*Watcher).watchKubesharkSecret.func3()
      /app/pkg/kubernetes/watcher.go:306 +0x44
  k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/controller.go:239 +0x63
  k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
      <autogenerated>:1 +0x1b
  k8s.io/client-go/tools/cache.(*processorListener).run.func1()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:978 +0x2a1
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:226 +0x41
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:227 +0xc4
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:204 +0x10a
  k8s.io/apimachinery/pkg/util/wait.Until()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:161 +0x9b
  k8s.io/client-go/tools/cache.(*processorListener).run()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:972 +0x38
  k8s.io/client-go/tools/cache.(*processorListener).run-fm()
      <autogenerated>:1 +0x33
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:72 +0x86

Goroutine 129 (running) created at:
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:70 +0xe4
  k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:802 +0x1ed
  k8s.io/client-go/tools/cache.(*sharedProcessor).run()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:806 +0x44
  k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
      <autogenerated>:1 +0x3d
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run.(*Group).StartWithChannel.func4()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:55 +0x38
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:72 +0x86

Goroutine 68 (running) created at:
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:70 +0xe4
  k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:802 +0x1ed
  k8s.io/client-go/tools/cache.(*sharedProcessor).run()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:806 +0x44
  k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
      <autogenerated>:1 +0x3d
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run.(*Group).StartWithChannel.func4()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:55 +0x38
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:72 +0x86`,
		`WARNING: DATA RACE
Write at [REDACTED] by [REDACTED]:
  github.com/kubeshark/hub/server/license.AddNode()
      /app/server/license/nodes.go:13 +[REDACTED]
  github.com/kubeshark/hub/pkg/kubernetes.(*Watcher).handleNodeObject()
      /app/pkg/kubernetes/watcher.go:1043 +[REDACTED]
  github.com/kubeshark/hub/pkg/kubernetes.(*Watcher).watchAllNodes.func3()
      /app/pkg/kubernetes/watcher.go:489 +[REDACTED]
  k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/controller.go:239 +[REDACTED]
  k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
      <autogenerated>:1 +[REDACTED]
  k8s.io/client-go/tools/cache.(*processorListener).run.func1()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:978 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:226 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:227 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:204 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.Until()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:161 +[REDACTED]
  k8s.io/client-go/tools/cache.(*processorListener).run()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:972 +[REDACTED]
  k8s.io/client-go/tools/cache.(*processorListener).run-fm()
      <autogenerated>:1 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:72 +[REDACTED]

Previous read at [REDACTED] by [REDACTED]:
  github.com/kubeshark/hub/server/license.GetNodeCount()
      /app/server/license/nodes.go:40 +[REDACTED]
  github.com/kubeshark/hub/server/license.Check()
      /app/server/license/license.go:143 +[REDACTED]
  github.com/kubeshark/hub/pkg/kubernetes.SyncSecret()
      /app/pkg/kubernetes/config.go:637 +[REDACTED]
  github.com/kubeshark/hub/pkg/kubernetes.(*Watcher).watchKubesharkSecret.func3()
      /app/pkg/kubernetes/watcher.go:306 +[REDACTED]
  k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/controller.go:239 +[REDACTED]
  k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
      <autogenerated>:1 +[REDACTED]
  k8s.io/client-go/tools/cache.(*processorListener).run.func1()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:978 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:226 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:227 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:204 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.Until()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/backoff.go:161 +[REDACTED]
  k8s.io/client-go/tools/cache.(*processorListener).run()
      /root/.cache/go-build/k8s.io/client-go@v0.30.2/tools/cache/shared_informer.go:972 +[REDACTED]
  k8s.io/client-go/tools/cache.(*processorListener).run-fm()
      <autogenerated>:1 +[REDACTED]
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /root/.cache/go-build/k8s.io/apimachinery@v0.30.2/pkg/util/wait/wait.go:72 +[REDACTED]`,
	},
}

func TestClean(t *testing.T) {
	for _, row := range data {
		redacted := redact(row.log)
		assert.Equal(t, row.redacted, redacted)
	}
}
